# Generated by Django 2.0.6 on 2019-04-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='amount_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='redirect_to',
            field=models.URLField(default='http://'),
        ),
    ]
