# Generated by Django 2.0.6 on 2019-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190420_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
