# Generated by Django 2.0.6 on 2019-04-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190406_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='redirect_to',
            field=models.URLField(),
        ),
    ]
