# Generated by Django 2.0.6 on 2019-04-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190406_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='amount_of_views',
            new_name='amount_of_visits',
        ),
    ]
